# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/l/liupiye/cs427/aria

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/l/liupiye/cs427/aria

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/l/liupiye/cs427/aria/CMakeFiles /home/l/liupiye/cs427/aria//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/l/liupiye/cs427/aria/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Aria

# Build rule for target.
Aria: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Aria
.PHONY : Aria

# fast build rule for target.
Aria/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/build
.PHONY : Aria/fast

src/ai_system.o: src/ai_system.cpp.o
.PHONY : src/ai_system.o

# target to build an object file
src/ai_system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/ai_system.cpp.o
.PHONY : src/ai_system.cpp.o

src/ai_system.i: src/ai_system.cpp.i
.PHONY : src/ai_system.i

# target to preprocess a source file
src/ai_system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/ai_system.cpp.i
.PHONY : src/ai_system.cpp.i

src/ai_system.s: src/ai_system.cpp.s
.PHONY : src/ai_system.s

# target to generate assembly for a file
src/ai_system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/ai_system.cpp.s
.PHONY : src/ai_system.cpp.s

src/common.o: src/common.cpp.o
.PHONY : src/common.o

# target to build an object file
src/common.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/common.cpp.o
.PHONY : src/common.cpp.o

src/common.i: src/common.cpp.i
.PHONY : src/common.i

# target to preprocess a source file
src/common.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/common.cpp.i
.PHONY : src/common.cpp.i

src/common.s: src/common.cpp.s
.PHONY : src/common.s

# target to generate assembly for a file
src/common.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/common.cpp.s
.PHONY : src/common.cpp.s

src/components.o: src/components.cpp.o
.PHONY : src/components.o

# target to build an object file
src/components.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/components.cpp.o
.PHONY : src/components.cpp.o

src/components.i: src/components.cpp.i
.PHONY : src/components.i

# target to preprocess a source file
src/components.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/components.cpp.i
.PHONY : src/components.cpp.i

src/components.s: src/components.cpp.s
.PHONY : src/components.s

# target to generate assembly for a file
src/components.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/components.cpp.s
.PHONY : src/components.cpp.s

src/game_level.o: src/game_level.cpp.o
.PHONY : src/game_level.o

# target to build an object file
src/game_level.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/game_level.cpp.o
.PHONY : src/game_level.cpp.o

src/game_level.i: src/game_level.cpp.i
.PHONY : src/game_level.i

# target to preprocess a source file
src/game_level.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/game_level.cpp.i
.PHONY : src/game_level.cpp.i

src/game_level.s: src/game_level.cpp.s
.PHONY : src/game_level.s

# target to generate assembly for a file
src/game_level.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/game_level.cpp.s
.PHONY : src/game_level.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/physics_system.o: src/physics_system.cpp.o
.PHONY : src/physics_system.o

# target to build an object file
src/physics_system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/physics_system.cpp.o
.PHONY : src/physics_system.cpp.o

src/physics_system.i: src/physics_system.cpp.i
.PHONY : src/physics_system.i

# target to preprocess a source file
src/physics_system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/physics_system.cpp.i
.PHONY : src/physics_system.cpp.i

src/physics_system.s: src/physics_system.cpp.s
.PHONY : src/physics_system.s

# target to generate assembly for a file
src/physics_system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/physics_system.cpp.s
.PHONY : src/physics_system.cpp.s

src/render_system.o: src/render_system.cpp.o
.PHONY : src/render_system.o

# target to build an object file
src/render_system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/render_system.cpp.o
.PHONY : src/render_system.cpp.o

src/render_system.i: src/render_system.cpp.i
.PHONY : src/render_system.i

# target to preprocess a source file
src/render_system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/render_system.cpp.i
.PHONY : src/render_system.cpp.i

src/render_system.s: src/render_system.cpp.s
.PHONY : src/render_system.s

# target to generate assembly for a file
src/render_system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/render_system.cpp.s
.PHONY : src/render_system.cpp.s

src/render_system_init.o: src/render_system_init.cpp.o
.PHONY : src/render_system_init.o

# target to build an object file
src/render_system_init.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/render_system_init.cpp.o
.PHONY : src/render_system_init.cpp.o

src/render_system_init.i: src/render_system_init.cpp.i
.PHONY : src/render_system_init.i

# target to preprocess a source file
src/render_system_init.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/render_system_init.cpp.i
.PHONY : src/render_system_init.cpp.i

src/render_system_init.s: src/render_system_init.cpp.s
.PHONY : src/render_system_init.s

# target to generate assembly for a file
src/render_system_init.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/render_system_init.cpp.s
.PHONY : src/render_system_init.cpp.s

src/tiny_ecs.o: src/tiny_ecs.cpp.o
.PHONY : src/tiny_ecs.o

# target to build an object file
src/tiny_ecs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/tiny_ecs.cpp.o
.PHONY : src/tiny_ecs.cpp.o

src/tiny_ecs.i: src/tiny_ecs.cpp.i
.PHONY : src/tiny_ecs.i

# target to preprocess a source file
src/tiny_ecs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/tiny_ecs.cpp.i
.PHONY : src/tiny_ecs.cpp.i

src/tiny_ecs.s: src/tiny_ecs.cpp.s
.PHONY : src/tiny_ecs.s

# target to generate assembly for a file
src/tiny_ecs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/tiny_ecs.cpp.s
.PHONY : src/tiny_ecs.cpp.s

src/tiny_ecs_registry.o: src/tiny_ecs_registry.cpp.o
.PHONY : src/tiny_ecs_registry.o

# target to build an object file
src/tiny_ecs_registry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/tiny_ecs_registry.cpp.o
.PHONY : src/tiny_ecs_registry.cpp.o

src/tiny_ecs_registry.i: src/tiny_ecs_registry.cpp.i
.PHONY : src/tiny_ecs_registry.i

# target to preprocess a source file
src/tiny_ecs_registry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/tiny_ecs_registry.cpp.i
.PHONY : src/tiny_ecs_registry.cpp.i

src/tiny_ecs_registry.s: src/tiny_ecs_registry.cpp.s
.PHONY : src/tiny_ecs_registry.s

# target to generate assembly for a file
src/tiny_ecs_registry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/tiny_ecs_registry.cpp.s
.PHONY : src/tiny_ecs_registry.cpp.s

src/utils.o: src/utils.cpp.o
.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

src/world_init.o: src/world_init.cpp.o
.PHONY : src/world_init.o

# target to build an object file
src/world_init.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/world_init.cpp.o
.PHONY : src/world_init.cpp.o

src/world_init.i: src/world_init.cpp.i
.PHONY : src/world_init.i

# target to preprocess a source file
src/world_init.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/world_init.cpp.i
.PHONY : src/world_init.cpp.i

src/world_init.s: src/world_init.cpp.s
.PHONY : src/world_init.s

# target to generate assembly for a file
src/world_init.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/world_init.cpp.s
.PHONY : src/world_init.cpp.s

src/world_system.o: src/world_system.cpp.o
.PHONY : src/world_system.o

# target to build an object file
src/world_system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/world_system.cpp.o
.PHONY : src/world_system.cpp.o

src/world_system.i: src/world_system.cpp.i
.PHONY : src/world_system.i

# target to preprocess a source file
src/world_system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/world_system.cpp.i
.PHONY : src/world_system.cpp.i

src/world_system.s: src/world_system.cpp.s
.PHONY : src/world_system.s

# target to generate assembly for a file
src/world_system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Aria.dir/build.make CMakeFiles/Aria.dir/src/world_system.cpp.s
.PHONY : src/world_system.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Aria"
	@echo "... src/ai_system.o"
	@echo "... src/ai_system.i"
	@echo "... src/ai_system.s"
	@echo "... src/common.o"
	@echo "... src/common.i"
	@echo "... src/common.s"
	@echo "... src/components.o"
	@echo "... src/components.i"
	@echo "... src/components.s"
	@echo "... src/game_level.o"
	@echo "... src/game_level.i"
	@echo "... src/game_level.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/physics_system.o"
	@echo "... src/physics_system.i"
	@echo "... src/physics_system.s"
	@echo "... src/render_system.o"
	@echo "... src/render_system.i"
	@echo "... src/render_system.s"
	@echo "... src/render_system_init.o"
	@echo "... src/render_system_init.i"
	@echo "... src/render_system_init.s"
	@echo "... src/tiny_ecs.o"
	@echo "... src/tiny_ecs.i"
	@echo "... src/tiny_ecs.s"
	@echo "... src/tiny_ecs_registry.o"
	@echo "... src/tiny_ecs_registry.i"
	@echo "... src/tiny_ecs_registry.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
	@echo "... src/world_init.o"
	@echo "... src/world_init.i"
	@echo "... src/world_init.s"
	@echo "... src/world_system.o"
	@echo "... src/world_system.i"
	@echo "... src/world_system.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

